# Generated by Django 5.0.7 on 2024-08-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
