# Generated by Django 5.0.7 on 2024-08-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
