# Generated by Django 5.0.7 on 2024-08-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_remove_dog_age_remove_dog_breed_remove_dog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dog',
            name='breed',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='dog',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
